//need to put special definitions for certain data structures in a separate .java tab

enum OS {MACOSX, WINDOWS};

enum SERIALPORTS {RFID_1_COMPORT, RFID_2_COMPORT, CAPTOUCH_1_COMPORT, CAPTOUCH_2_COMPORT, 
STEPPER_1_COMPORT, STEPPER_2_COMPORT, STEPPER_3_COMPORT, NEOPIXEL_1_COMPORT, NEOPIXEL_2_COMPORT,
LINEAR_ACT_1_COMPORT, LINEAR_ACT_2_COMPORT };


